[package]
name = "xapo2ks"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2"
itertools = "0.14.0"
derive-new = "0.7"
clap = { version = "4.5", features = ["derive"] }
rust_decimal = "1.36"
time = { version = "0.3", features = ["macros", "formatting", "parsing"] }
csv = "1.3"
